# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Docker.
        id: docker_cache
        uses: actions/cache@v3
        with:
          path: ./docker_files
          key: ${{ runner.os }}-docker-udo1
          restore-keys: |
            ${{ runner.os }}-docker-udo1-
        env:
          TRANS_PATH: /home/runner/work/ci_test/ci_test/all_folder
      - name: Build docker
        run: |
          echo "run build docker"
          (
            pwd && ls -haltr && mkdir docker_files &&
            echo "Start building docker image" &&
            docker build -t udo .  ./docker_files &&
            echo "Finished all"
          )